[sc-5895] add low-resources preset
groundcover-com/cli pull request #118
Opened 2022-12-11 15:54 UTC by steb-veksler

2022-12-19 14:14 UTC, noamApps reviewed
tested on ? (kind/minikube/k3d)

2022-12-21 07:13 UTC, steb-veksler commented
> tested on ? (kind/minikube/k3d)

k3s is working, kind and minikube have ring buffer errors on flora

2023-01-02 12:04 UTC, noamApps requested changes
remove vmagent-backend

2023-01-02 18:23 UTC, noamApps requested changes

2023-01-02 18:23 UTC, noamApps commented on cmd/deploy.go
> +	if err = mergo.Merge(&chartValues, defaultChartValues, mergo.WithSliceDeepCopy); err != nil {
remove from pr

2023-01-02 18:23 UTC, noamApps commented on cmd/deploy.go
> +		messageFormat := "We get it, you like things light 🪁\n   But since you’re deploying on a %s we’ll have to limit some of our features to make sure it’s smooth sailing.\n   For the full groundcover e
move to const

2023-01-02 18:33 UTC, noamApps approved these changes

2023-01-02 18:33 UTC, merged