generate grafana service account token command
groundcover-com/cli pull request #255
Opened 2023-09-14 13:16 UTC by noamApps

2023-09-18 13:14 UTC, steb-veksler requested changes

2023-09-18 13:14 UTC, steb-veksler commented on pkg/auth/sa_token.go
> +	SAToken string `json:"token" validate:"required"`
```suggestion
	Token string `json:"token" validate:"required"`
```

2023-09-19 12:02 UTC, noamApps commented on pkg/auth/sa_token.go
> +	SAToken string `json:"token" validate:"required"`
fixed

2023-09-19 12:36 UTC, steb-veksler approved these changes

2023-09-19 12:37 UTC, merged