[sc-4942] - added aws cli version check
groundcover-com/cli pull request #97
Opened 2022-09-21 17:13 UTC by maxlevinps

2022-09-22 10:01 UTC, steb-veksler requested changes

2022-09-25 07:13 UTC, steb-veksler requested changes

2022-09-25 07:13 UTC, steb-veksler commented on pkg/k8s/cluster.go
> +	awsCliVersion, err := semver.Parse(matches[1])
switch awsCliVersion.Major {
	case 1:
		return awsCliVersion.GTE(MinSupportedAwsCliV1Version)
	case 2:
		return awsCliVersion.GTE(MinSupportedAwsCliV2Version)
	default:
		return true
	}

2022-09-25 07:13 UTC, steb-veksler commented on pkg/k8s/cluster.go
> +func ValidateAwsCliVersionSupported(version string) bool {
private method

2022-09-25 07:13 UTC, steb-veksler commented on pkg/k8s/cluster.go
> +	AwsCliV2                    = semver.Version{Major: 2, Minor: 0, Patch: 0}
remove

2022-09-25 07:13 UTC, steb-veksler commented on pkg/k8s/cluster.go
> +	AwsCliV3                    = semver.Version{Major: 3, Minor: 0, Patch: 0}
remove

2022-10-06 16:13 UTC, noamApps approved these changes

2022-10-06 16:29 UTC, merged